services:
  nodejs-server:
    container_name: streamerdotbot-irl-speaker-node
    build:
      context: .
      dockerfile: Dockerfile
    image: node:lts-alpine  # Use the official Node.js image
    restart: unless-stopped
    working_dir: /usr/src/app
    # ports:
    #   - 3000:3000
    volumes:
      - ./:/usr/src/app  # Mount local directory to container (adjust path as needed)
      - ${SOUNDS_PATH}:/usr/src/app/sounds
      - ${TTS_PATH}:/usr/src/app/tts
      - ./documents:/usr/src/app/documents
    environment:
      - NODE_ENV=production  # Set Node.js environment to production
    command: ["npm", "start"]  # Command to start the server

  cloudflared-irl:
    container_name: streamerdotbot-irl-speaker-cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for cloudflared
    # ports:
      # - 8080:8080
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: ["tunnel", "--no-autoupdate", "run", "--token", "${CLOUDFLARE_TUNNEL_TOKEN}"]
